id: opecha:P001810
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD76618
  title: རྔ་བ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་བདམས་བསྒྲིགས། དེབ་གསུམ་པ
  volume: ''
  author: ''
