id: P001810
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD76618
  title: རྔ་བ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་བདམས་བསྒྲིགས། དེབ་གསུམ་པ
  author: ''
  volumes:
    4ffd8c8e1a4c402589d0119e73d769a7:
      image_group_id: I1KG1437
      title: ''
      volume_number: 1
      total_pages: 194
