id: I7B14DA9F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:31:16+00:00'
last_modified: '2022-06-07T15:14:09.862770+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD76618
  title: རྔ་བ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་བདམས་བསྒྲིགས། དེབ་གསུམ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CAEC:
      image_group_id: I1KG1437
      title: ''
      total_pages: 194
      order: 1
      base_file: CAEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
