id: I7B14DA9F
legacy_id: P001810
ocr_import_info:
  bdrc_scan_id: W1PD76618
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T11:30:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:56:48.382411+00:00'
last_modified: 2022-09-01 12:56:55.554122
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD76618
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD76618
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྔ་བ་བོད་རིགས་རང་སྐྱོང་ཁུལ་གྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་ཡིག་བདམས་བསྒྲིགས། དེབ་གསུམ་པ།
  author: བཙན་ལྷ་ངག་དབང་།
statistics:
  ocr_word_mean_confidence_index: 0.7044004272198032
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I1KG1437:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1437
      total_pages: 194
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1437.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7044004272198032
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
